# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Shary Dela Cruz
title: Full Stack Software Engineer | Data Engineer
email: shary.delacruz@outlook.com

# Dark Mode (true/false/never)
darkmode: never

# Social links
github_username: shary-dc
linkedin_username: shary-dc
leetcode_username: shary-dc

# About Section
about_title: About Me
about_profile_image: images/me2.jpeg
about_content: | 
  Hello, my name is Shary Dela Cruz, I'm a full stack software engineer / data engineer with over 10 years experience specialising in .NET/C# development and building data pipelines and data visualizations. I just moved to Sydney, Australia but I was previously working for Crédit Agricole Corporate and Investment Bank (CA-CIB) in Singapore on their Compliance IT team.
  
  I like writing clean and efficient code. While working with CA-CIB, I was promoted to Technical Lead and part of my responsibilities involve creating an efficient developer experience using DevOps tools and techniques. I have worked with a range of languages and frameworks and I am always looking forward to learning opportunities.

content:
  # Skills Section
  - title: Skills
    layout: text
    content: |
      - **Languages**: C#, JavaScript, TypeScript, PowerShell, Python
      - **Frameworks**:	.NET (all flavors), Entity Framework, Angular, MSBI Stack (SSIS, SSRS, SSAS), PowerBI
      - **Database**:	SQL Server, PostgreSQL, Oracle
      - **Tools**: Git, GitLab, GitHub, Azure DevOps, Nexus, Artifactory, ArgoCD, HashiCorp Vault, xUnit, SonarQube, CheckMarx, Docker, Kubernetes, Jira, Confluence
      - **Soft Skills**: Tech Leadership and Mentoring (25+ developers), Agile Methodologies, Effective Communication

  # Experience Section
  - title: Experience
    layout: list
    content:
      - layout: left
        title: Crédit Agricole Corporate and Investment Bank
        link: https://www.ca-cib.com
        sub_title: Technical Lead | Data Engineer + Full-Stack Software Engineer
        caption: April 2015 – September 2024
        description: |
          **Technical Lead (4 years)**  
          - Expanded a team from 5 to over 20 developers with diverse expertise in .NET, Angular, MSBI, and Java Spark by actively leading recruitment, onboarding, and mentorship programs.
          - Led the architectural redesign of a medium-scale credit review workflow application (100+ users), resolving performance and security issues.
          - Designed and developed a wide range of applications, including console, web, and API solutions, while creating and implementing shared packages to promote code reusability and consistency across projects.
          - Led the containerization of legacy applications by refactoring them into cloud-ready solutions and transitioning deployments from on-premise servers to an on-premise cloud infrastructure, enhancing scalability and operational efficiency.
          
          **Full-Stack Software Engineer + Data Engineer (5 years)**  
          - Improved development time by implementing DevOps processes: migrated application documentations from Sharepoint to Confluence, configured CI/CD pipelines using GitLab/Azure DevOps, automated good coding standards using CheckMarx and SonarQube.
          - Actively worked in Agile software development environments with international teams, leveraging the SCRUM framework.
          - Developed a high-performing ETL console application using .NET/C#, handling large-scale data integration.
          - Built web applications to support risk analysis for KYC processes, incorporating configurable rules and parameters.
          - Designed SQL-optimized ETL pipelines and implemented database partitioning using SSIS and Oracle PL/SQL.
      - layout: left
        title: Willis Towers Watson
        link: https://www.wtwco.com/
        caption: October 2013 – April 2015
        sub_title: Business Intelligence Developer
        description: |
          - Designed and developed dashboards, enabling stakeholders to make informed business decisions.
          - Created aesthetically pleasing and high-performing reports tailored to end-user requirements.
      - layout: left
        title: Ducen Infotek
        caption: June 2012 – September 2013
        sub_title: BI Developer
        description: |
          - Led the implementation of ETL pipelines to centralize sales and inventory data.
          - Created visually appealing reports, enabling the marketing team to enhance client presentations.
      - layout: left
        title: PCM
        caption: November 2011 – April 2012
        sub_title: Java Developer
        description: |
          - Enhanced e-commerce website search functionality by integrating new features with Java and Apache Solr.

  # Education Section
  - title: Education
    layout: list
    content:
      - layout: left
        title: Technological Institute of the Philippines
        caption: April 2013
        sub_title: Bachelor of Science in Information Technology
      - layout: left
        title: University of Helsinki (Open University)
        caption: November 2024
        sub_title: Python Programming 2024
  
  # Certification Section
  - title: Certifications
    layout: list
    content:
      - layout: left
        title: Python Programming
        caption: 2024
        sub_title: University of Helsinki

      - layout: left
        title: Data Analyst Career Path
        sub_title: Microsoft Learn

      - layout: left
        title: Power BI Data Analyst Associate
        sub_title: Microsoft (in progress)

      - layout: left
        title: SQL (Advanced) Certificate
        sub_title: HackerRank
  
  - title: When I'm Not Programming
    layout: text
    content: |
      Alongside my interests in data and software engineering some of my other interests and hobbies are:
      - Gaming (PS5, Switch)
      - Board Games (my favorite is Avalon !)
      - Hiking (I'm going to try to hike all of the trails in NSW)
      - Arts (drawing and watercolor painting)

# Footer
footer_show_references: true
references_title: References available on request

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
