# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Shary Dela Cruz
title: Data Engineer | Full Stack Software Engineer
email: shary.delacruz@outlook.com
website: linkedin.com/in/shary-dc

# Dark Mode (true/false/never)
darkmode: never

# Social links
github_username: shary-dc
linkedin_username: shary-dc

# About Section
about_title: About Me
about_profile_image: images/me.jfif
about_content: | 
  Full-stack developer and data engineering specialist with extensive experience building solutions across web, API, and data environments. My toolkit includes .NET/C#, Angular, SQL, Python, and the Microsoft BI stack (SSRS, SSIS, SSAS), enabling me to create seamless data pipelines and high-impact reports. I’ve led a team of 25+ developers, I have modernized legacy projects, architected several data, web and console applications, and designed CI/CD pipelines that elevate code quality and deployment speed. Recently, I’ve learned PowerBI, adding new layers of data visualization and automation to my skillset.

# Experience Section
content:
  - title: Experience
    layout: list
    content:
      - layout: left
        title: Crédit Agricole Corporate and Investment Bank
        link: https://www.ca-cib.com
        sub_title: Technical Lead | Data Engineer + Full-Stack Software Engineer
        caption: April 2015 – September 2024
        quote: >
          Delivering innovative solutions and modernized BI applications in the banking domain.
        description: |
          **Technical Lead (4 years)**  
          - Managed and mentored a team of 20+ developers, scaling from 5.  
          - Modernized BI applications, reducing runtime by 30% through SQL optimization.  
          - Led architectural redesigns to improve performance and security.  
          - Transitioned legacy applications to modular architecture.  
          - Implemented CI/CD pipelines and secure coding standards.  

          **Data Engineer + Full-Stack Software Engineer (5 years)**  
          - Developed ETL applications and SQL-optimized pipelines.  
          - Built web applications for KYC risk analysis.  
          - Enhanced deployment with Docker, Kubernetes, and CI/CD pipelines.  
          - Delivered high-performing SSRS reports for business decision-making.  

      - layout: left
        title: Towers Watson Global Business Services
        caption: October 2013 – April 2015
        sub_title: BI Developer
        quote: >
          Creating impactful dashboards for informed business decisions.
        description: |
          - Designed and developed data-driven dashboards.  
          - Created visually appealing reports tailored to user needs.  

      - layout: left
        title: Ducen Infotek
        caption: June 2012 – September 2013
        sub_title: BI Developer
        quote: >
          Centralizing and visualizing critical business data.
        description: |
          - Implemented ETL pipelines to centralize sales and inventory data.  
          - Designed impactful client-facing reports.  

      - layout: left
        title: PCM
        caption: November 2011 – April 2012
        sub_title: Java Developer
        quote: >
          Enhancing e-commerce functionalities for seamless user experience.
        description: |
          - Enhanced search functionality using Java and Apache Solr. 

# Footer
footer_show_references: true
references_title: Available upon request

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
