# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Shary Dela Cruz
title: Data Engineer | BI Developer
email: shary.delacruz@outlook.com
website: linkedin.com/in/shary-dc

# Dark Mode (true/false/never)
darkmode: never

# Social links
github_username: shary-dc
linkedin_username: shary-dc

# About Section
about_title: About Me
about_profile_image: images
