# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Shary Dela Cruz
title: Data Engineer | BI Developer
email: shary.delacruz@outlook.com
website: linkedin.com/in/shary-dc

# Dark Mode (true/false/never)
darkmode: never

# Social links
github_username: shary-dc
linkedin_username: shary-dc

# About Section
about_title: About Me
about_profile_image: images/me.jfif
about_content: | 
  Experienced Data Engineer with expertise in developing ETL pipelines, modernizing BI applications, and creating reports and dashboards for data-driven decision-making. Skilled in SQL, Python, and Power BI, with a track record of enabling actionable insights through advanced data analytics and visualization.

# Footer
footer_show_references: true
references_title: Available upon request

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
